name: Docker Image ElasticVue
on:
  push:
    paths:
      - .trigger
      - Dockerfile
      - .github/workflows/build.yml

jobs:
  elasticvue:
    name: ElasticVue
    runs-on: ubuntu-latest

    steps:

      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/rollupdev/elasticvue:latest
